version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:13-buster-node-browsers-legacy

    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target
